export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_ORIGINS_SUCCESS = "GET_ORIGINS_SUCCESS";
export const SET_CHANGED_PRODUCT = "SET_CHANGED_PRODUCT";
export const FIRST_UPLOAD_INIT = "FIRST_UPLOAD_INIT";
export const ADD_PRODUCT = "ADD_PRODUCT";