export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const INCREMENT_ITEMS_COUNT = "INCREMENT_ITEMS_COUNT";
export const DECREMENT_ITEMS_COUNT = "DECREMENT_ITEMS_COUNT";
export const REMOVE_ITEMS_FROM_CART = "REMOVE_ITEMS_FROM_CART";
export const SAVE_PRODUCT_DETAILS = "SAVE_PRODUCT_DETAILS";